import Head from 'next/head'
import Image from 'next/image'
import Sidebar from './sidebar.jsx'
import styles from '../styles/Home.module.css'

export default function Layout({children}) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Sidebar />
        <div className={styles.content}>
          <div className={styles.contentbox}>{children}</div>
        </div>
      </div>
    </>
  )
}